name: LEDE Compilation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext wget unzip python2

      - name: Download LEDE Source Code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy .config
        run: |
          cd lede
          cp ../.config .config

      - name: Install Python Dependencies
        run: |
          cd lede
          pip2 install -r scripts/openwrt_packit/requirements.txt

      - name: Build LEDE Kernel Package
        run: |
          cd lede
          python2 scripts/openwrt_packit/openwrt_packit.py

      - name: Package OpenWrt Firmware
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMVIRT: lede/bin/targets/*/*/*rootfs.tar.gz
          PACKAGE_SOC: r68s
          KERNEL_VERSION_NAME: 5.15.95_6.1.15
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        with:
          tag: openwrt_armvirt_v8_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is OpenWrt firmware for Armvirt 64
            * Firmware information
            Default IP: 192.168.1.1
            Default username: root
            Default password: password
